### ISSUE TITLE
core-kotlin is not compatible with the latest OkHttp version

### ISSUE THREAD

**Issue by dawidhyzy** [aws-amplify/amplify-android#2778]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```kotlin
// Put output below this line
implementation(libs.amplifyframework.core) // com.amplifyframework:core-kotlin:2.15.1
implementation(libs.amplifyframework.aws.auth.cognito) // com.amplifyframework:aws-auth-cognito:2.15.1
implementation(libs.okhttp) // com.squareup.okhttp3:okhttp:5.0.0-alpha.14
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------

Build time:   2024-03-22 15:52:46 UTC
Revision:     650af14d7653aa949fce5e886e685efc9cf97c10

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.9 (JetBrains s.r.o. 17.0.9+7-b1087.7)
OS:           Mac OS X 14.4.1 aarch64
```

</details>

### Describe the bug

After upgrading OkHttp to 5.0.0-alpha.14 app crash with
```
java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/JvmCallExtensionsKt;
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.roundTrip(OkHttpEngine.kt:51)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.internal.ManagedHttpClientEngine.roundTrip(Unknown Source:2)
                                                                                                    	at aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invokeSuspend(SdkHttpClient.kt:44)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ab2cfdd, Dispatchers.Default]
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.JvmCallExtensionsKt" on path: DexPathList[[zip file "/data/app/~~IAL8PvUtBlvnpkVvFmHIww==/com.smith.production.development-6WBupxve8b7XQGyKB-wpWw==/base.apk"],nativeLibraryDirectories=[/data/app/~~IAL8PvUtBlvnpkVvFmHIww==/com.smith.production.development-6WBupxve8b7XQGyKB-wpWw==/lib/arm64, /data/app/~~IAL8PvUtBlvnpkVvFmHIww==/com.smith.production.development-6WBupxve8b7XQGyKB-wpWw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 9 more
```

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment]
We need Smithy and Kotlin SDK to release new versions that are compatible with the OkHttp changes. There's not much we can do until those become available.

**Comment by mattcreaser** [comment]
I've posted a bug to the Smith library here: https://github.com/smithy-lang/smithy-kotlin/issues/1068

**Comment by dawidhyzy** [comment]
Thanks @mattcreaser 
Looks like the update was just released https://github.com/smithy-lang/smithy-kotlin/releases/tag/v1.2.0

**Comment by mattcreaser** [comment]
We will be test this change through the first part of next week, if all goes well we'll get it into an upcoming release.

**Comment by tylerjroach** [comment]
The change has been made in Amplify Android 2.18.0
